### ISSUE TITLE
playframework 2.6.2 & scala 2.12

### ISSUE THREAD

**Issue by Enalmada** [dwickern/sbt-classloader-leak-prevention#2]
This module looks interesting.  Request for latest play/scala support!

**Comment by Enalmada** [comment]
Note that it seems like just updating dependency versions (sbt/play/scala/scalatestplus-play) is enough to make everything work without any code changes for latest play/scala.  (I just couldn't figure out how to appropriately keep the older versions of play working with the scripted test setup going on but hopefully that will be easy for ya)

**Comment by dwickern** [comment]
That's exactly right. Play 2.6 is source compatible but binary incompatible with 2.5. I tried a bit to cross-compile for both Play library versions but SBT didn't make this easy. I think it might be easier to use reflection.

**Comment by Enalmada** [comment]
Ah that is too bad...well I am totally biased because I have upgraded to 2.6.x already but it might make sense from efficiency/maintainability to just to deprecate those older play versions and just remove them from the project...version 0.4 is out on maven for anyone that needs it.

**Comment by benmccann** [comment]
I implemented Play 2.7 support here: https://github.com/shaagerup/sbt-classloader-fix/pull/1
